# Generated by Django 4.1.2 on 2022-12-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.CharField(max_length=20)),
                ('Class', models.CharField(max_length=20)),
                ('Admission', models.IntegerField()),
                ('EnglishScore', models.IntegerField()),
                ('MathsScore', models.IntegerField()),
                ('ScienceScore', models.IntegerField()),
                ('KiswahiliScore', models.IntegerField()),
                ('SSCREScore', models.IntegerField()),
                ('TotalScore', models.IntegerField()),
            ],
        ),
    ]
