# Generated by Django 4.1.2 on 2023-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='img',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
